kind: Deployment
apiVersion: apps/v1
metadata:
  name: code-with-quarkus
  namespace: workshop
  labels:
    app: code-with-quarkus
    app.kubernetes.io/component: code-with-quarkus
    app.kubernetes.io/instance: code-with-quarkus
    app.kubernetes.io/name: code-with-quarkus
    app.kubernetes.io/part-of: sample-app
    app.openshift.io/runtime: quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-with-quarkus
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: code-with-quarkus
        deployment: code-with-quarkus
    spec:
      containers:
        - name: code-with-quarkus
          image: 'image-registry.openshift-image-registry.svc:5000/workshop/code-with-quarkus:latest'
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
